### ISSUE TITLE
Error executing NLTK cell in lecture 11 on GH Runner

### ISSUE THREAD

**Issue by trgardos** [tools4ds/DS701-Course-Notes#34]
When executing lecture 11 qmd file on the github runner as part of the Actions workflow, it is now getting  [error](https://github.com/tools4ds/DS701-Course-Notes/actions/runs/10442113733/job/28914063202#step:10:821), copied below. It seemed to be working locally, but I went ahead and added `nltk.download('wordnet')` but it still doesn't seem to find it.

I found this [issue](https://github.com/nltk/nltk/issues/3028) on github.com/nltk/nltk/issues, that indicates that in an earlier version, nltk wouldn't unzip the downloaded wordnet.zip, and that a workaround was to manually unzip it.

This wasn't a problem with my local environment which has nltk==3.8.1. The runner apparently installs with nltk==3.9.1, so I'm trying again with nltk==3.8.1 in requirements.

```
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/runner/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.4/x64/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.4/x64/share/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.4/x64/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by trgardos** [comment]
Seems down versioning to nltk==3.8.1 did the trick per PR #33

**Comment by 123walid** [comment]
I am still getting the same error even after setting the nltk=3.8.1

**Comment by dvdalilue** [comment]
I was facing the same issue, turns out they introduce a bug in version 3.9.1. There was a hotfix 3 days ago: https://github.com/nltk/nltk/commit/7d1cbc71441f607daea0894333912268e2911cab
