### ISSUE TITLE
move storage and retrieval of cs-506-midterm-a1-b1

### ISSUE THREAD

**Issue by trgardos** [tools4ds/DS701-Course-Notes#7]
One of the files for the Recommender lecture is not included. Need to store somewhere else and fetch.

> From Mark
> 
> Just FYI if you want to obtain the file in the future you can:
>  
> pip install kaggle
> put the attached file in your ~/.kaggle
> kaggle competitions download -c cs-506-midterm-a1-b1
> 

[kaggle.json](https://github.com/user-attachments/files/16071492/kaggle.json)

**Comment by trgardos** [comment]
temporarily commented out building notebook 20 on recommender systems so we can proceed with GitHub pages publishing.

**Comment by sladenheim** [comment]
I have an approach where the file is publicly available on my google drive. Users can then use gdown to download the file. We should discuss the pros and cons of this approach.

**Comment by trgardos** [comment]
An enhancement would be to cache the data file. Can mention that in a new issue.

For now, at least check and download in the notebook but perhaps also do it in Actions script
